module.exports = {
    colors: {
        col1: '#FFFDD0',
        text1: 'red',
        text2: 'grey',
        text3: 'black',
        textgreen: 'green',
        mtg:'#694fad',
    },
    titles: {
        title1: 40,
        btntxt: 20,
    },
    btn1: {
        width: '80%',
        height: 50,
        backgroundColor: '#694fad',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        color: 'white',
        marginBottom: 10,
    },
    btn2: {
        width: 150,
        height: 50,
        backgroundColor: '#694fad',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        color: 'white',
        margin: 10,
        alignSelf: 'center',
    },
    hr80: {
        width: '80%',
        borderBottomColor: '#694fad',
        borderBottomWidth: 1,
        marginVertical: 20,
    },
    veg: {
        width: 20,
        height: 20,
        borderRadius: 20,
        backgroundColor: 'green',
    },
    nonveg: {
        width: 20,
        height: 20,
        borderRadius: 20,
        backgroundColor: 'red',
    },
    navbtn: {
        backgroundColor: '#694fad',
        width: 50,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        borderRadius: 50,
        borderTopLeftRadius: 0,
    },
    navbtnin: {
        color: 'white',
    },
    navbtnout: {
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 10,
    },
    incdecbtn: {

        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        elevation: 10,
        padding: 10,
        color: 'white',
        fontSize: 20,
        fontWeight: 'bold',

    },
    incdecinput: {

        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        padding: 10,
        width: 50,
        marginHorizontal: 10,
        fontSize: 20,
    },
    incdecout: {
        flexDirection: 'row',
        alignItems: 'center',
        margin: 10,
    },
}